---
driver:
  name: podman
platforms:
  - name: ubuntu2204
    # image: ubuntu:22.04
    image: jrei/systemd-ubuntu:22.04
    privileged: true
    command: /lib/systemd/systemd
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
